language: c

compiler:
  - gcc
  #- clang

addons:
  apt:
    packages:
    - zlib1g-dev
    - glusterfs-common
    
#before_install:
#  - sudo apt-get update && sudo apt-get install -y zlib-devel

script:
  - cmake .
  - make
